apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-data-worker
    environment: Development
  name: account-data-worker
  namespace: exchange
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: account-data-worker
  sessionAffinity: None
  type: ClusterIP
